ecommerce_backend/customer_app/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from customer_app.api import views as customer_views

urlpatterns = [
    path('register/', customer_views.register, name = "register"),
    path('login/', obtain_auth_token, name = "login"),
    path('logout/', customer_views.logout, name = "logout"),
    
    path('profile/', customer_views.ProfileAV.as_view(), name = "profile"),
    path('wishlist/', customer_views.WishListGV.as_view(), name = 'wishlist'),
    path('order-list/', customer_views.OrderListGV.as_view(), name = 'order-list'),
    path('order-details/<int:pk>', customer_views.OrderDetailsGV.as_view(), name = 'order-details'),
]

ecommerce_backend/customer_app/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views

from customer_app import views as customer_views

urlpatterns = [
    path('register/', customer_views.register, name = "register"),
    path('login/', auth_views.LoginView.as_view(template_name = "customer_app/login.html"), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = "customer_app/logout.html"), name = "logout"),
    
    path('profile/', customer_views.profile, name = "profile"),
    path('wishlist/', customer_views.wishList, name = 'wishlist'),
    path('order-list/', customer_views.orderList, name = 'order-list'),
    path('order-details/<int:pk>', customer_views.OrderDetailView.as_view(), name = 'order-details'),
]

ecommerce_backend/ecommerce_backend/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include("admin_app.api.urls")),
    path('background-task/', include('background_task_app.api.urls')),
    path('customer/', include('customer_app.api.urls')),
    path("", include("store_app.api.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_backend/customer_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class AdminUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default='', related_name='adminUser')
    
    def __str__(self) -> str:
        return self.user.username
    
    
class Customer(models.Model):
    # username, email, password -> in the 'user' table
    user = models.OneToOneField(User, on_delete=models.CASCADE, default='', related_name='customer', null=True, blank=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    image = models.ImageField(default='default.png', upload_to="profile_pics")
    
    def __str__(self) -> str:
        if self.user is None:
            return f"Customer ID = {self.pk} (customer.user is NONE)"
        else:
            return f"username = {str(self.user.username)} | email = {str(self.user.email)}"

ecommerce_backend/store_app/models.py
from django.db import models
from django.db.models import Q

from customer_app.models import Customer

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(default=0.0)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self) -> str:
        return f"Product: id = {self.id} | name = {self.name}"
  
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        
        return url
    
    @property
    def isInWishlist(self):
        wishlist_items = self.wishlistitem_set.all()
        return len(wishlist_items) > 0
    
    @property
    def wishlist_item_customer_id_list(self):
        customer_id_list = self.wishlistitem_set.values_list('customer', flat=True)
        print('returning...  user_id_list = ', customer_id_list)
        return customer_id_list
    
    @property
    def get_current_unit_price(self):
        return self.stock_set.all().first().current_unit_price
    
    @property
    def get_current_discount(self):
        return self.stock_set.all().first().current_discount
    
    @property
    def get_current_selling_price(self):
        return self.stock_set.all().first().get_current_selling_price
    
    @property
    def get_stock_info(self):
        return self.stock_set.all().first()
    
    
class Cart(models.Model):
    customer = models.OneToOneField(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    transaction_id = models.CharField(max_length=100, null=True)
    
    def __str__(self) -> str:
        return f'Cart ID: {self.id}    -   Customer: {self.customer}'
    
    @property
    def shipping(self):
        shipping = False
        cart_items = self.cartitem_set.all()
        
        for item in cart_items:
            if item.product.digital == False:
                shipping = True
                break
        return shipping
    
    @property
    def get_cart_total(self):
        cart_items = self.cartitem_set.filter(is_checked=True)
        return sum([item.get_total for item in cart_items]) 
    
    @property
    def get_all_cart_item_count(self):
        cart_items = self.cartitem_set.all()
        return sum([item.quantity for item in cart_items]) 
    
    @property
    def get_checked_item_count(self):
        cart_items = self.cartitem_set.filter(is_checked=True)
        return sum([item.quantity for item in cart_items])
    
    
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=1, null=True, blank=True)
    is_checked = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'CartItem ID: {self.id}  ->   Name: {self.product.name}'
    
    @property
    def get_total(self):
        return self.quantity * self.product.price
    
    @property
    def get_stock_info(self):
        return Stock.objects.get(product=self.product)
        
    
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True) 
    date_added = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField('Modified in', auto_now=True)
    
    def __str__(self) -> str:
        return self.address
    

class Order(models.Model):
    STATUS_CHOICES = (
        (0, 'Waiting for Payment'),
        (1, 'Preparing Order'),
        (2, 'Order is Prepared'),
        (3, 'Order in Shipping'),
        (4, 'Order is Delivered'),
        (5, 'Cancelled')
    )
    PAYMENT_OPTION_CHOICES = (
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Bkash', 'Bkash'),
    )
    
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order_status = models.IntegerField('Order Status', choices=STATUS_CHOICES, default=0)
    payment_option = models.CharField('Payment Options', choices=PAYMENT_OPTION_CHOICES, max_length=20, default='Cash On Delivery')
    transaction_id = models.CharField(max_length=100, null=True)
    is_shipped = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField('Created in', auto_now_add=True)
    modified = models.DateTimeField('Modified in', auto_now=True)
    
    class Meta:
        verbose_name = 'Order'
        ordering = ('-created',)
    
    def __str__(self) -> str:
        return f'Order #{self.pk} - Customer: {self.customer.user} - Status: {self.order_status}'
    
    @property
    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)
    
    @property
    def shipping(self):
        shipping = False
        order_items = self.orderitem_set.all()
        
        for item in order_items:
            if item.product.digital == False:
                shipping = True
                break
        return shipping
    
    @property
    def get_order_total(self):
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total 
    
    @property
    def get_number_of_items(self):
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total 

    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'OrderItem ID: {self.id}  ->   Name: {self.product.name}'
    
    @property
    def get_total(self):
        return self.quantity * self.product.stock.current_selling_price
    
    
class WishListItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'WishListItem: product-name = {self.product.name} | customer = {self.customer}'
    
    
class PurchasedItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    unit_price = models.FloatField()
    purchase_price = models.FloatField()
    quantity = models.IntegerField(default = 0)
    product_source_name = models.CharField(max_length=200, null=True)
    buying_time = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'PurchasedItem: product-name = {self.product.name} | unit_price = {self.unit_price}  |  quantity = {self.quantity}'
    
    @property
    def total_unit_price(self):
        return self.unit_price * self.quantity
    
    @property
    def total_purchase_price(self):
        return self.purchase_price * self.quantity
    
        
class SoldItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    unit_price = models.FloatField(default=0.0)
    purchase_price = models.FloatField(default=0.0)
    quantity = models.IntegerField(default = 0)
    discount = models.FloatField(default=0.0)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'order = {self.order} | SoldItem: product-name = {self.product.name}'
    
    @property
    def unit_selling_price(self):
        return self.unit_price - self.discount
    
    @property
    def total_unit_price(self):
        return self.unit_price * self.quantity
    
    @property
    def total_purchase_price(self):
        return self.purchase_price * self.quantity
    
    @property
    def total_discount(self):
        return self.discount * self.quantity
    
    @property
    def total_selling_price(self):
        return self.unit_selling_price * self.quantity
    
    @property
    def unit_profit(self):
        return self.unit_selling_price - self.purchase_price
    
    @property
    def total_profit(self):
        return self.unit_profit * self.quantity
    
    
class Stock(models.Model):
    product = models.OneToOneField(Product, on_delete=models.PROTECT)
    current_discount = models.FloatField(default=0.0)
    order_limit = models.IntegerField(default=50)
    
    def __str__(self) -> str:
        return f'Stock: product-name = {self.product.name}'
    
    @property
    def current_unit_price(self):
        all_purchased_items = PurchasedItem.objects.filter(product=self.product)
        total_purchase_count = len(all_purchased_items)
        return 0 if total_purchase_count == 0 else all_purchased_items[total_purchase_count - 1].unit_price
    
    @property
    def current_selling_price(self):
        return self.current_unit_price - self.current_discount
    
    @property
    def current_purchase_price(self):
        all_purchased_items = PurchasedItem.objects.filter(product=self.product)
        total_purchase_count = len(all_purchased_items)

ecommerce_backend/customer_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from customer_app.models import Customer

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User 
        fields = ['username', 'email', 'password1', 'password2']
        
        
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User 
        fields = ['username', 'email']
        
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer 
        fields = ['image']

ecommerce_backend/customer_app/api/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView

from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework import status, generics

from .serializers import RegistrationSerializer, CustomerSerializer
from customer_app.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from store_app.utils import cartData, getWishListItems, getTrackInfoList, getCartItemList, getStockInfoList
from store_app.models import Order, OrderItem, WishListItem
from store_app.api.serializers import OrderSerializer, WishListItemSerializer
from customer_app.models import AdminUser, Customer

# Create your views here.
@api_view(['POST',])
def register(request):
    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)
        data = {}
        
        if serializer.is_valid():
            account = serializer.save()
            token = Token.objects.get(user=account).key
            status_code = status.HTTP_201_CREATED
            
            data['Response'] = "User created successfully!"
            data['username'] = account.username
            data['email'] = account.email
            data['token'] = token
        else:
            data = serializer.errors
            status_code = status.HTTP_400_BAD_REQUEST
        
        return Response(data, status=status_code)
    

@api_view(['POST'])
def logout(request):
    if request.method == 'POST':
        request.user.auth_token.delete()
        return Response(status=status.HTTP_200_OK)
    

class ProfileAV(APIView):
    # TODO: couldn't find a way to implement generics.RetrieveAPIView
    # TODO: if a generic view would be implemented, there would be less code and also less errors
    # serializer_class = CustomerSerializer
    # queryset = Customer.objects.filter(user=self.request.user).first()
    # def get_queryset(self):
    #     return Customer.objects.filter(user=self.request.user).first()
    
    def get(self, request):
        try:
            customer_info = Customer.objects.filter(user=request.user).first()
            serializer = CustomerSerializer(customer_info) # add "context={'request': request}" into the argument-list for HyperlinkedRelatedField
            print(f"serializer.data = {serializer.data}")
            return Response(serializer.data, status=status.HTTP_200_OK)
        except:
            return Response(status.HTTP_400_BAD_REQUEST)
    
    def put(self, request):
        customer_info = Customer.objects.filter(user=request.user).first()
        serializer = CustomerSerializer(customer_info, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    
class WishListGV(generics.ListAPIView):
    serializer_class = WishListItemSerializer
    
    def get_queryset(self):
        return WishListItem.objects.filter(customer=self.request.user.customer)
    
    
class OrderListGV(generics.ListAPIView):
    serializer_class = OrderSerializer
    
    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user.customer)
    

class OrderDetailsGV(generics.RetrieveAPIView):
    serializer_class = OrderSerializer
    
    def get_queryset(self):
        pk = self.kwargs['pk']
        return Order.objects.filter(pk=pk)

ecommerce_backend/templates/customer_app/login.html
{% extends "store_app/main.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href={% url "register" %}>Sign Up Now</a>
            </small>
        </div>
    </div>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

ecommerce_backend/templates/customer_app/logout.html
{% extends "store_app/main.html" %}
{% block content %}
    <h2>You have been logged out!</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href={% url 'login' %}>Log In again.</a>
        </small>
    </div>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

ecommerce_backend/templates/customer_app/order-details.html
{% extends 'store_app/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <!-- For 'tracking' portion
                Source: https://www.bootdey.com/snippets/view/Shop-Order-Tracking#html -->
            <div class="box-element padding-bottom-3x mb-3 mt-3">
                <div class="card">
                  <div class="p-4 text-center text-white text-lg rounded-top" style="background-color:#343a40 !important"><span class="text-uppercase">Order ID - </span><span class="text-medium">#{{ order.id }}</span></div>
                  <div class="d-flex flex-wrap flex-sm-nowrap justify-content-between py-3 px-2 bg-order-overview" style="background-color:#f5f5f5">
                    <div class="w-100 text-center py-1 px-2"><span class="text-medium">Status:</span> <strong>{{ order.get_order_status_display }}</strong></div>
                    <div class="w-100 text-center py-1 px-2"><span class="text-medium">Created Date:</span> {{ order.created }}</div>
                  </div>
                  <div class="card-body">
                    <div class="steps d-flex flex-wrap flex-sm-nowrap justify-content-between padding-top-2x padding-bottom-1x">
                        {% for trackInfo in trackInfoList %} 
                            {% if trackInfo.is_completed %}
                            <div class="step completed">
                            {% else %}
                            <div class="step">
                            {% endif %}
                                <div class="step-icon-wrap">
                                <div class="step-icon"><i class="{{ trackInfo.icon }}"></i></div>
                                </div>
                                <h4 class="step-title">{{ trackInfo.title }}</h4>
                            </div>
                        {% endfor%}
                    </div>
                    {% if order.order_status == 0 %}
                        <a id="complete-payment" style="display: block; margin-left: auto; margin-right: auto; width: 40%" class="btn btn-success">Complete Your Payment</a>
                    {% endif %}
                  </div>
                </div>
            </div>
        
        

            <div class="box-element mb-5">
                {% comment %} <a  class="btn btn-outline-dark pl-5 pr-5" href="{% url 'store' %}">Order Id: <strong>#{{order.id}}</strong></a> {% endcomment %}
                {% comment %} <br> {% endcomment %}
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{ order.get_number_of_items }} </strong></h5></th>
                        <th><h5>Total:<strong> ${{order.get_order_total|floatformat:2}} </strong></h5></th>
                    </tr>
                </table>
                <br/>
                {% comment %} <br/> {% endcomment %}

                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                        <div style="flex:2"><p>{{item.product.name}}</p></div>
                        <div style="flex:1"><p>{{item.product.price|floatformat:2}} </p></div>
                        <div style="flex:1">
                            <p class="quantity">{{item.quantity}}</p>
                        </div>
                        <div style="flex:1"><p>{{item.get_total|floatformat:2}} </p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        {% if order.order_status == 0 %}
            document.getElementById("complete-payment").addEventListener("click", function(e){
                completePayment()
            })
        {% endif %}
        function completePayment(){
            var url = '/complete-payment/'
            fetch(url, {
                method: 'POST',
                headers:{
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    'order_id': {{ order.id }},
                }),
            })
            .then((response) => response.json())
            .then((data)=>{
                console.log('Success: ', data)
                alert("Payment Completed!")
                window.location.reload();
            })
        }
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/order-details.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

ecommerce_backend/templates/customer_app/order-list.html
{% extends 'store_app/main.html' %}
{% load static %}
{% block content %}
    {% if orders|length == 0 %}
        <h1 style="float:center;">No order history found!</h1>
    {% else %}
        {% for order in orders %}
            {% if order.get_number_of_items > 0 %}
                <div class="box-element m-3">
                    <a  class="btn btn-outline-dark pl-5 pr-5">Order Id: <strong>#{{order.id}}</strong></a>
                    <br>
                    <br>
                    <table class="table">
                        <tr>
                            <th><h5>Items: <strong>{{ order.get_number_of_items }} </strong></h5></th>
                            <th><h5>Total:<strong> ${{order.get_order_total|floatformat:2}} </strong></h5></th>
                            <th>
                                {% if order.order_status != 5 %}
                                    <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'order-details' order.id %}">See Details</a>
                                {% else %}
                                    <a  style="float:right; margin:5px;" class="btn btn-outline-warning">Cancelled</a>
                                {% endif %}
                            </th>
                        </tr>
                        <td style="border:0; padding-top:0;">
                            <h5>Status: <strong> {{ order.get_order_status_display }} </strong></h5>
                        </td>   

                        {% if order.order_status == 4 %}
                            <td style="border:0; padding-top:0;">
                                <h5>Completed: <strong> {{ order.modified|date:"F d, Y" }} </strong></h5>
                            </td>
                        {% endif %}
                    </table>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

ecommerce_backend/templates/customer_app/profile.html
{% extends "store_app/main.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div> 
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update Profile</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
  </div>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}

ecommerce_backend/templates/customer_app/register.html
{% extends "store_app/main.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href={% url 'login' %}>Sign In</a>
            </small>
        </div>
    </div>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">	
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock content %}